### ISSUE TITLE
potato: how to express a contract

### ISSUE THREAD

**Issue by vdemeester** [vdemeester/vegetable-resolver#2]
In the [`README.md`](https://github.com/vdemeester/vegetable-resolver#task-type-and-injection) we talke about task type as contract.

> The idea behind *Task types* is more easily explained with an
> example. Let's assume we have a "general" `Pipeline` that is building
> an OCI image, pushing it on some registry, scan the content of the
> image and run tests against it.  There is *a lot* of options to build
> an image, and most likely, we don't necessarily care about which tool
> is used.

And the content is a bit like the following : 

```yaml
# This is a partial Task definition with the only
# required field.
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    potato.tekton.dev/type: builder
spec:
  params:
  - name: IMAGE
    description: Name (reference) of the image to build
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image built
  - name: IMAGE_URL
    description: Digest of the image built
```

The question then is, how do we express the contract and where do we store it / them.

- CRDs, a `TaskContract` CRD that would hold the bare minimum thing required.
- We could explore using [`cue`](https://cuelang.org/) here
- Storage could happen in configmap, or in CRDs
